### ISSUE TITLE
All Rentals doesn't show any rental listings

### ISSUE THREAD

**Issue by anthonynikhilreddy** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2#125]
All Rentals doesn't show any rental listings. It would be great if the user could see listings irrescpective of whether he searches for a particular borough.

![image](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/assets/54550550/ff2c8ca3-eaba-422d-acf7-31c8f0dfdf91)

**Comment by aru456** [comment]
Mentioned in the testing doc, if it is going to a place holder page its not developed yet
