### ISSUE TITLE
if I want to just to filter based on a price the search button is not enabled.

### ISSUE THREAD

**Issue by anthonynikhilreddy** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2#126]
As a user, if I want to just to filter based on a price the search button is not enabled.

![image](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/assets/54550550/9cec016b-7ad0-45d2-810d-f8c07576cf3e)

**Comment by aru456** [comment]
You should be able to see All(NYC) option in search, you can use that
The search is restricted for only neighborhoods and boroughs so it is disabled if you do not select any option
