### ISSUE TITLE
Setup backend database

### ISSUE THREAD

**Issue by maludee** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2#16]
Set up database and initial tables:
- User/landlord table should exist to store account information for registered users/landlords
- Admin table should exist to store admin login information 
- Passwords are securely stored / hashed     

DOD:
User/Landlord tables exists in AWS RDS. Admin table also exists. Passwords are securely stored.

**Comment by vamshinaik309** [comment]
I have setup the postgresSQL in AWS RDS, and connected it to our application.
