### ISSUE TITLE
User - Sign up

### ISSUE THREAD

**Issue by SiriErrabelli** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2#2]
As a user, I want to be able to create an account by providing an nyu email and password.

**Comment by maludee** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/INET-Wednesday-Spring2024-65c2720b329216000fc08fb8/issues/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/2?planning-poker) with Zenhub @maludee

**Comment by SiriErrabelli** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/INET-Wednesday-Spring2024-65c2720b329216000fc08fb8/issues/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/2?planning-poker) with Zenhub @maludee @aru456 @vamshinaik309
