### ISSUE TITLE
Landlord - Sign up

### ISSUE THREAD

**Issue by maludee** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2#3]
As a landlord, I want to sign up for a landlord account using email, password and document of ownership(verified manually by admin)

**Comment by SiriErrabelli** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/INET-Wednesday-Spring2024-65c2720b329216000fc08fb8/issues/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/3?planning-poker) with Zenhub @aru456 @maludee @vamshinaik309

**Comment by maludee** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/INET-Wednesday-Spring2024-65c2720b329216000fc08fb8/issues/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/3?planning-poker) with Zenhub @qf2050

**Comment by aru456** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/INET-Wednesday-Spring2024-65c2720b329216000fc08fb8/issues/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/3?planning-poker) with Zenhub @SiriErrabelli
