### ISSUE TITLE
Landlord - Login

### ISSUE THREAD

**Issue by maludee** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2#4]
As a landlord, once verified I want to log into my account using the email and password.
A landlord should be directed to a landlord-specific page after logging in. 
A landlord should not be directed or able to view the user page. 
- Note - URL string should be /landlord

DOD:
Landlord is successfully able to login using his credentials. Landlord is successfully redirected to landlord home page after logging in. Landlord cannot view user home page when he modifies the URL string manually.

**Comment by SiriErrabelli** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/INET-Wednesday-Spring2024-65c2720b329216000fc08fb8/issues/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/4?planning-poker) with Zenhub @aru456 @maludee @vamshinaik309
