### ISSUE TITLE
User - Login

### ISSUE THREAD

**Issue by SiriErrabelli** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2#5]
As a user, I want to be able to log into my account using my nyu email and password
As a user, I want to receive and appropriate error message for incorrect login attempts
as a user, I want to be able to navigate to a user page after log in (and not be able to see a landlord page). 

DOD : User can Login successfully using  his NYU email and password. User receives error message if he tries to login using incorrect credentials. User is successfully redirected to user home page after successful login.

**Comment by SiriErrabelli** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/INET-Wednesday-Spring2024-65c2720b329216000fc08fb8/issues/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/5?planning-poker) with Zenhub @aru456 @maludee @vamshinaik309

**Comment by vamshinaik309** [comment]
Created Login for User.
