### ISSUE TITLE
Landlord reset password 

### ISSUE THREAD

**Issue by maludee** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2#6]
As a landlord, I want to reset my account via email if I forget the password.

**Comment by SiriErrabelli** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/INET-Wednesday-Spring2024-65c2720b329216000fc08fb8/issues/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/6?planning-poker) with Zenhub @aru456 @maludee @vamshinaik309
