### ISSUE TITLE
Landlord post new listings

### ISSUE THREAD

**Issue by maludee** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2#73]
As a landlord, I want to post new listings with detailed descriptions, photos, price, amenities and availability dates to attract potential renters.

- When a landlord submits a form, the data needs to populate in the database
- There should be some basic data validation that takes place

**Comment by qf2050** [comment]
Do I need to create the database? I'm not sure how to create a new table in the online database

**Comment by qf2050** [comment]
I found a RentalListings class in the models.Should I Use it.

**Comment by maludee** [comment]
@qf2050 the data posted by landlords should probably go into the users_rental_listings table, which is where all the listings data is stored right now. 
not sure about the models, I would post in slack asking the group

**Comment by qf2050** [comment]
I saw users/models.py:80 has been annotated. If I want to implement this feature, it seems like I need to add foreign keys

**Comment by qf2050** [comment]
I am a little confused why the ForeignKey  Landlord ID is blocked. so the users_rental_listings has no  Landlord ID?
